import "@/app/styles/global.scss"
import "@/app/styles/fonts.scss"
import ServerProvider from "@/app/components/ServerProvider";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        </head>
        <body>
            <ServerProvider>
                {children}
            </ServerProvider>
        </body>
        </html>
    )
}
